// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-objects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { z } from "npm:zod@^4.4.3";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_objects_default = defineTool({
  name: "search_celestial_objects",
  title: "Search celestial objects",
  description: "Search the Cosmic Frame deep-sky catalog by name, common name, catalog id (e.g. 'M31', 'NGC 7000'), or constellation. Returns basic identity, position, magnitude, size, and type.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Text to search: catalog id, common name, or constellation."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const like = `%${query.replace(/[%_]/g, "\\$&")}%`;
    const { data, error } = await sb().from("celestial_objects").select(
      "catalog_id,common_name,constellation,obj_type,magnitude,size_max,ra,dec,scientific_notation"
    ).or(
      `catalog_id.ilike.${like},common_name.ilike.${like},constellation.ilike.${like},search_aliases.ilike.${like},scientific_notation.ilike.${like}`
    ).order("magnitude", { ascending: true, nullsFirst: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-object.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_object_default = defineTool2({
  name: "get_celestial_object",
  title: "Get celestial object",
  description: "Fetch full details for one deep-sky object by its catalog id (e.g. 'M31', 'NGC 7000', 'IC 1396'). Includes photo score, moon tolerance, recommended filter, exposure guides, and best months.",
  inputSchema: {
    catalog_id: z2.string().trim().min(1).describe("Catalog id such as 'M31', 'NGC 7000', 'IC 1396'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ catalog_id }) => {
    const { data, error } = await sb2().from("celestial_objects").select("*").ilike("catalog_id", catalog_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No object found for catalog id "${catalog_id}".` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { object: data }
    };
  }
});

// src/lib/mcp/tools/nearest-dark-sites.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";

// src/lib/dark-sites.ts
var DARK_SITES = [
  // Europe
  { name: "Pic du Midi", lat: 42.9369, lng: 0.1411, bortle: 1, country: "FR", designation: "IDA Dark Sky Reserve" },
  { name: "Alqueva", lat: 38.22, lng: -7.16, bortle: 1, country: "PT", designation: "IDA Dark Sky Reserve" },
  { name: "C\xE9vennes National Park", lat: 44.35, lng: 3.58, bortle: 2, country: "FR", designation: "IDA Dark Sky Reserve" },
  { name: "Galloway Forest Park", lat: 55.08, lng: -4.63, bortle: 2, country: "GB", designation: "IDA Dark Sky Park" },
  { name: "Kerry International", lat: 51.77, lng: -9.85, bortle: 2, country: "IE", designation: "IDA Dark Sky Reserve" },
  { name: "Zselic Starry Sky Park", lat: 46.23, lng: 17.77, bortle: 2, country: "HU", designation: "IDA Dark Sky Park" },
  { name: "Westhavelland", lat: 52.72, lng: 12.33, bortle: 3, country: "DE", designation: "IDA Dark Sky Reserve" },
  { name: "Brecon Beacons", lat: 51.88, lng: -3.44, bortle: 3, country: "GB", designation: "IDA Dark Sky Reserve" },
  { name: "Vercors Regional Natural Park", lat: 44.95, lng: 5.45, bortle: 3, country: "FR" },
  { name: "Chartreuse", lat: 45.35, lng: 5.82, bortle: 3, country: "FR" },
  { name: "Ard\xE8che", lat: 44.6, lng: 4.35, bortle: 3, country: "FR" },
  { name: "Aosta Valley", lat: 45.74, lng: 7.32, bortle: 2, country: "IT" },
  { name: "Hortob\xE1gy National Park", lat: 47.58, lng: 21.15, bortle: 2, country: "HU", designation: "IDA Dark Sky Park" },
  // North America
  { name: "Cherry Springs State Park", lat: 41.66, lng: -77.82, bortle: 1, country: "US", designation: "IDA Gold Tier" },
  { name: "Big Bend National Park", lat: 29.25, lng: -103.25, bortle: 1, country: "US", designation: "IDA Dark Sky Park" },
  { name: "Natural Bridges NM", lat: 37.6, lng: -110.01, bortle: 1, country: "US", designation: "IDA Dark Sky Park" },
  { name: "Death Valley National Park", lat: 36.46, lng: -116.87, bortle: 1, country: "US", designation: "IDA Gold Tier" },
  { name: "Jasper National Park", lat: 52.87, lng: -117.95, bortle: 1, country: "CA", designation: "IDA Dark Sky Preserve" },
  { name: "Mont-M\xE9gantic", lat: 45.45, lng: -71.15, bortle: 2, country: "CA", designation: "IDA Dark Sky Reserve" },
  { name: "Grand Canyon National Park", lat: 36.1, lng: -112.11, bortle: 2, country: "US", designation: "IDA Dark Sky Park" },
  { name: "Joshua Tree National Park", lat: 33.87, lng: -115.9, bortle: 2, country: "US" },
  { name: "Bryce Canyon National Park", lat: 37.59, lng: -112.19, bortle: 2, country: "US", designation: "IDA Dark Sky Park" },
  { name: "Great Basin National Park", lat: 38.98, lng: -114.3, bortle: 1, country: "US", designation: "IDA Dark Sky Park" },
  // Southern Hemisphere & other
  { name: "NamibRand Nature Reserve", lat: -25.07, lng: 15.99, bortle: 1, country: "NA", designation: "IDA Gold Tier" },
  { name: "Aoraki Mackenzie", lat: -44, lng: 170.47, bortle: 1, country: "NZ", designation: "IDA Dark Sky Reserve" },
  { name: "Atacama Desert", lat: -24.63, lng: -70.4, bortle: 1, country: "CL" },
  { name: "Warrumbungle National Park", lat: -31.28, lng: 149, bortle: 2, country: "AU", designation: "IDA Dark Sky Park" }
];
function distanceKm(lat1, lng1, lat2, lng2) {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLng = (lng2 - lng1) * Math.PI / 180;
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

// src/lib/mcp/tools/nearest-dark-sites.ts
var nearest_dark_sites_default = defineTool3({
  name: "nearest_dark_sites",
  title: "Nearest dark sites",
  description: "Return the closest low-light-pollution observing sites (IDA Dark Sky Parks/Reserves and other curated sites) to a given latitude/longitude, sorted by distance.",
  inputSchema: {
    lat: z3.number().min(-90).max(90).describe("Observer latitude in decimal degrees."),
    lng: z3.number().min(-180).max(180).describe("Observer longitude in decimal degrees."),
    limit: z3.number().int().min(1).max(20).default(5).describe("Max sites to return (1-20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ lat, lng, limit }) => {
    const results = DARK_SITES.map((s) => ({ ...s, distance_km: Math.round(distanceKm(lat, lng, s.lat, s.lng)) })).sort((a, b) => a.distance_km - b.distance_km).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { sites: results }
    };
  }
});

// src/lib/mcp/tools/astro-weather.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var astro_weather_default = defineTool4({
  name: "astro_weather_forecast",
  title: "Astronomy weather forecast",
  description: "Astrophotography-oriented weather forecast for a location: hourly cloud cover (low/mid/high), temperature, humidity, dew point, and wind for the next ~48 hours. Powered by Open-Meteo (public data, no key).",
  inputSchema: {
    lat: z4.number().min(-90).max(90).describe("Latitude in decimal degrees."),
    lng: z4.number().min(-180).max(180).describe("Longitude in decimal degrees.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ lat, lng }) => {
    const url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&hourly=temperature_2m,relative_humidity_2m,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed_10m,dew_point_2m&forecast_days=2&timezone=auto`;
    try {
      const res = await fetch(url);
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `Open-Meteo error ${res.status}` }],
          isError: true
        };
      }
      const data = await res.json();
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { forecast: data }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Fetch failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cosmic-frame-mcp",
  title: "Cosmic Frame",
  version: "0.1.0",
  instructions: "Public astrophotography planning tools from Cosmic Frame. Search the deep-sky catalog, look up an object's imaging metadata (magnitude, size, moon tolerance, recommended filter, exposure guides), find the nearest dark-sky sites to a location, and get an astronomy-oriented weather forecast. All tools are read-only and use public data.",
  tools: [search_objects_default, get_object_default, nearest_dark_sites_default, astro_weather_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
