// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-objects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { z } from "npm:zod@^4.4.3";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_objects_default = defineTool({
  name: "search_celestial_objects",
  title: "Search celestial objects",
  description: "Search the Cosmic Frame deep-sky catalog by name, common name, catalog id (e.g. 'M31', 'NGC 7000'), or constellation. Returns basic identity, position, magnitude, size, and type.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Text to search: catalog id, common name, or constellation."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const like = `%${query.replace(/[%_]/g, "\\$&")}%`;
    const { data, error } = await sb().from("celestial_objects").select(
      "catalog_id,common_name,constellation,obj_type,magnitude,size_max,ra,dec,scientific_notation"
    ).or(
      `catalog_id.ilike.${like},common_name.ilike.${like},constellation.ilike.${like},search_aliases.ilike.${like},scientific_notation.ilike.${like}`
    ).order("magnitude", { ascending: true, nullsFirst: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-object.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_object_default = defineTool2({
  name: "get_celestial_object",
  title: "Get celestial object",
  description: "Fetch full details for one deep-sky object by its catalog id (e.g. 'M31', 'NGC 7000', 'IC 1396'). Includes photo score, moon tolerance, recommended filter, exposure guides, and best months.",
  inputSchema: {
    catalog_id: z2.string().trim().min(1).describe("Catalog id such as 'M31', 'NGC 7000', 'IC 1396'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ catalog_id }) => {
    const { data, error } = await sb2().from("celestial_objects").select("*").ilike("catalog_id", catalog_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No object found for catalog id "${catalog_id}".` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { object: data }
    };
  }
});

// src/lib/mcp/tools/nearest-dark-sites.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
import { DARK_SITES, distanceKm } from "npm:@/lib/dark-sites";
var nearest_dark_sites_default = defineTool3({
  name: "nearest_dark_sites",
  title: "Nearest dark sites",
  description: "Return the closest low-light-pollution observing sites (IDA Dark Sky Parks/Reserves and other curated sites) to a given latitude/longitude, sorted by distance.",
  inputSchema: {
    lat: z3.number().min(-90).max(90).describe("Observer latitude in decimal degrees."),
    lng: z3.number().min(-180).max(180).describe("Observer longitude in decimal degrees."),
    limit: z3.number().int().min(1).max(20).default(5).describe("Max sites to return (1-20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ lat, lng, limit }) => {
    const results = DARK_SITES.map((s) => ({ ...s, distance_km: Math.round(distanceKm(lat, lng, s.lat, s.lng)) })).sort((a, b) => a.distance_km - b.distance_km).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { sites: results }
    };
  }
});

// src/lib/mcp/tools/astro-weather.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var astro_weather_default = defineTool4({
  name: "astro_weather_forecast",
  title: "Astronomy weather forecast",
  description: "Astrophotography-oriented weather forecast for a location: hourly cloud cover (low/mid/high), temperature, humidity, dew point, and wind for the next ~48 hours. Powered by Open-Meteo (public data, no key).",
  inputSchema: {
    lat: z4.number().min(-90).max(90).describe("Latitude in decimal degrees."),
    lng: z4.number().min(-180).max(180).describe("Longitude in decimal degrees.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ lat, lng }) => {
    const url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&hourly=temperature_2m,relative_humidity_2m,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed_10m,dew_point_2m&forecast_days=2&timezone=auto`;
    try {
      const res = await fetch(url);
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `Open-Meteo error ${res.status}` }],
          isError: true
        };
      }
      const data = await res.json();
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { forecast: data }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Fetch failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cosmic-frame-mcp",
  title: "Cosmic Frame",
  version: "0.1.0",
  instructions: "Public astrophotography planning tools from Cosmic Frame. Search the deep-sky catalog, look up an object's imaging metadata (magnitude, size, moon tolerance, recommended filter, exposure guides), find the nearest dark-sky sites to a location, and get an astronomy-oriented weather forecast. All tools are read-only and use public data.",
  tools: [search_objects_default, get_object_default, nearest_dark_sites_default, astro_weather_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
