// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ytitrmdlmjpyhwkbpjvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aXRybWRsbWpweWh3a2JwanZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNDI2NjAsImV4cCI6MjA4NzYxODY2MH0.Uop61naJaDcEQ2jBwOuX7_boHUnWzw_JC3K7vISTeEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
